# Site settings
title: blog.mattiasgees.be
header-img: img/home.jpg
email: mattias.gees@gmail.com
description: "My personal blog."
baseurl: ""
url: "http://blog.mattiasgees.be"
twitter_username: MattiasGees
github_username:  MattiasGees
facebook_username:  mattias.gees
linkedin_username: mattiasgees

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
