title: blog.mattiasgees.be
email: mattias.gees@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.mattiasgees.be" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MattiasGees
github_username:  MattiasGees
linkedin_username: mattiasgees

markdown:           kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
